### ISSUE TITLE
views are supported only on couchbase buckets with couchstore storage backend

### ISSUE THREAD

**Issue by taskinozdemir** [couchbase/docs-sdk-dotnet#307]
Hello. We are using Couchbase Server Enterprise Edition 7.1.4 build 3601 in the server side and in sdk 3.4.9 in the client side. Our bucked is CouchbaseBucked with magma selected in the backend. Dynatrace one agent is present in the client servers. There are failed request to _design/p/view/p adress. 

{"error":"not_found","reason":"views are supported only on couchbase buckets with couchstore storage backend"}

Could you please help us to resolve this issue?

https://github.com/couchbase/docs-sdk-dotnet/assets/16115416/7ddd5de8-dee3-4257-b58c-a64ee430792c

**Comment by emilienbev** [comment]
Hi Taşkın! Unfortunately the Views service is not compatible with Magma storage backend, and only works with the Couchstore backend.
There is no plan to support Views on Magma in the future, see the warning on our [.NET SDK docs page](https://docs.couchbase.com/dotnet-sdk/current/concept-docs/understanding-views.html).

**Comment by taskinozdemir** [comment]
I know that and we do not have any views. Problem is when we make queries with sdk, it automatically call that page and took error. It is a huge problem for us. It spends to many time.

![image](https://github.com/couchbase/docs-sdk-dotnet/assets/16115416/2c3ab659-25ca-4e80-8bca-5678f283eeb6)

**Comment by RichardSmedley** [comment]
I see you've now taken this to a Support ticket - which is a much better route to finding the problem.  :+1: 

I'll close this issue against our docs site, but feel free to re-open. or open a ticket in JIRA against the docs if it turns out there's something we're missing here in the docs.
(Although if there is, Support will also contact docs)
